최댓값, 최솟값 설정하기
playground-code-review/flutter pull request #32
Opened 2021-01-11 11:22 UTC by HJ0711

clamp 함수를 이용하여 최댓값, 최솟값 설정해 보았습니다.

2021-01-11 23:09 UTC, deviankim requested changes

2021-01-11 23:09 UTC, deviankim commented on lib/my_home_page.dart
> +
counter 가 12 로 변경 되었다면 다시 내리려면 - 버튼을 두번 눌러야 값 변경되는 것이 보이겠군요.
내용 수정하시고 push 한번 해보시겠어요?

2021-01-13 22:32 UTC, closed without merging

2021-01-13 23:59 UTC, HJ0711 commented on lib/my_home_page.dart
> +
네, 수정되면 push 해 보겠습니다

2021-01-14 00:00 UTC, HJ0711 commented on lib/my_home_page.dart
> +
> counter 가 12 로 변경 되었다면 다시 내리려면 - 버튼을 두번 눌러야 값 변경되는 것이 보이겠군요.
> 내용 수정하시고 push 한번 해보시겠어요?

네, 수정되면 push 하겠습니다

2021-01-14 00:00 UTC, HJ0711 commented on lib/my_home_page.dart
> +
> counter 가 12 로 변경 되었다면 다시 내리려면 - 버튼을 두번 눌러야 값 변경되는 것이 보이겠군요.
> 내용 수정하시고 push 한번 해보시겠어요?

네, 수정하면 push 하겠습니다